blueprint:
  name: Grow Room Heater Control
  description: >
    Controls a grow room temperature based on lights ON/OFF,
    sensor validation, and absolute safety cutoffs.
  domain: automation

  input:
    temperature_sensor:
      name: Temperature Sensor
      selector:
        entity:
          domain: sensor

    heater_switch:
      name: Heater Switch
      selector:
        entity:
          domain: switch

    lights_switch:
      name: Lights Switch
      selector:
        entity:
          domain: switch

    day_temp_low:
      name: Day Temperature Low
      selector:
        entity:
          domain: input_number

    day_temp_high:
      name: Day Temperature High
      selector:
        entity:
          domain: input_number

    night_temp_low:
      name: Night Temperature Low
      selector:
        entity:
          domain: input_number

    night_temp_high:
      name: Night Temperature High
      selector:
        entity:
          domain: input_number

    absolute_max_temp:
      name: Absolute Maximum Temperature
      selector:
        entity:
          domain: input_number

    absolute_min_temp:
      name: Absolute Minimum Temperature
      selector:
        entity:
          domain: input_number

mode: restart

trigger:
  - platform: state
    entity_id:
      - !input temperature_sensor
      - !input lights_switch
      - !input day_temp_low
      - !input day_temp_high
      - !input night_temp_low
      - !input night_temp_high
      - !input absolute_max_temp
      - !input absolute_min_temp

action:

  # --- SENSOR INVALID FAILSAFE ---
  - choose:
      - conditions:
          - condition: state
            entity_id: !input temperature_sensor
            state:
              - "unknown"
              - "unavailable"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input heater_switch
          - stop: "Temperature sensor invalid"

  # --- ABSOLUTE MAX FAILSAFE ---
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input temperature_sensor
            above: !input absolute_max_temp
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input heater_switch
          - stop: "Absolute max temperature reached"

  # --- ABSOLUTE MIN FAILSAFE ---
  - choose:
      - conditions:
          - condition: numeric_state
            entity_id: !input temperature_sensor
            below: !input absolute_min_temp
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input heater_switch
          - stop: "Absolute min temperature reached"

  # --- CONFIGURATION SANITY CHECK ---
  - choose:

      # Day min >= Day max
      - conditions:
          - condition: numeric_state
            entity_id: !input day_temp_low
            above: !input day_temp_high
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input heater_switch
          - stop: "Invalid DAY temperature config (low >= high)"

      # Night min >= Night max
      - conditions:
          - condition: numeric_state
            entity_id: !input night_temp_low
            above: !input night_temp_high
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input heater_switch
          - stop: "Invalid NIGHT temperature config (low >= high)"

      # Absolute min >= Absolute max
      - conditions:
          - condition: numeric_state
            entity_id: !input absolute_min_temp
            above: !input absolute_max_temp
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input heater_switch
          - stop: "Invalid ABSOLUTE temperature config (min >= max)"

  # --- NORMAL CONTROL ---
  - choose:

      # DAY MODE
      - conditions:
          - condition: state
            entity_id: !input lights_switch
            state: "on"
        sequence:
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: !input temperature_sensor
                    below: !input day_temp_low
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input heater_switch

              - conditions:
                  - condition: numeric_state
                    entity_id: !input temperature_sensor
                    above: !input day_temp_high
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input heater_switch

      # NIGHT MODE
      - conditions:
          - condition: state
            entity_id: !input lights_switch
            state: "off"
        sequence:
          - choose:
              - conditions:
                  - condition: numeric_state
                    entity_id: !input temperature_sensor
                    below: !input night_temp_low
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input heater_switch

              - conditions:
                  - condition: numeric_state
                    entity_id: !input temperature_sensor
                    above: !input night_temp_high
                sequence:
                  - service: switch.turn_off
                    target:
                      entity_id: !input heater_switch
